name: main-cn

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python environment
      uses: ./.github/actions/setup-python

    - name: update-cn
      run: |
        git config --global user.email "1054329447@qq.com"
        git config --global user.name "Seniorious0"
        uv run ptil --check --remote new regular special
