name: weedy

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python environment
      uses: ./.github/actions/setup-python

    - name: weedy_high
      env:
        PTILOPSIS_USERNAME: ${{ secrets.PTILOPSIS_USERNAME }}
        PTILOPSIS_PASSWORD: ${{ secrets.PTILOPSIS_PASSWORD }}
        PTILOPSIS_SENTRY_DSN: ${{ secrets.PTILOPSIS_SENTRY_DSN }}
      run: uv run ptil weedy
