name: main-cn-force

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python environment
      uses: ./.github/actions/setup-python

    - name: update-cn-force
      run: |
        pip install -r requirements.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        python main.py --check --remote --force new regular special
