name: weedy

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python environment
      uses: ./.github/actions/setup-python

    - name: weedy_high
      run: uv run ptil weedy
