# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# git config user.email "1054329447@qq.com"
# git config user.name "Seniorious0"

name: main-cn

on:
  # push:
  #   branches: [ master ]
  # schedule:
  #   - cron: '0 8 * * *'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: update-cn
      run: |
        pip install -r requirements.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        python main.py --check --remote new regular special
